import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {Animals} from "./animals";
import {TableTitles} from "../tableTitles";
import {AlterRace} from "./raceTable";

export class AnimalTable extends Table{
    constructor(){
        let entries = [];
        entries.push(new TableEntry(Animals.Goat,1));
        entries.push(new TableEntry("armadillo",2));
        entries.push(new TableEntry("buffalo",3));
        entries.push(new TableEntry("capybara",4));
        entries.push(new TableEntry("badger",5));
        entries.push(new TableEntry("elephant",6));
        entries.push(new TableEntry("earth piglet",7));
        entries.push(new TableEntry("spot musang",8));
        entries.push(new TableEntry("ferret",9));
        entries.push(new TableEntry("gorilla",10));
        entries.push(new TableEntry("hamster",11));
        entries.push(new TableEntry("chicken",12));
        entries.push(new TableEntry("dog",13));
        entries.push(new TableEntry("jaguar",14));
        entries.push(new TableEntry("capuchin monkey",15));
        entries.push(new TableEntry("cat",16));
        entries.push(new TableEntry("coyote",17));
        entries.push(new TableEntry("lama",18));
        entries.push(new TableEntry("lion",19));
        entries.push(new TableEntry("lux",20));
        entries.push(new TableEntry("mole",21));
        entries.push(new TableEntry("hippo",22));
        entries.push(new TableEntry("horse",23));
        entries.push(new TableEntry("rat",24));
        entries.push(new TableEntry("reindeer",25));
        entries.push(new TableEntry("rhino",26));
        entries.push(new TableEntry("rob",27));
        entries.push(new TableEntry("chimpanzee",28));
        entries.push(new TableEntry("platypus",29));
        entries.push(new TableEntry("platypus",30));
        entries.push(new TableEntry("skunk",31));
        entries.push(new TableEntry("gibbon",32));
        entries.push(new TableEntry("elk",33));
        entries.push(new TableEntry("alpaca",34));
        entries.push(new TableEntry("giraffe",35));
        entries.push(new TableEntry("plumploris",36));
        entries.push(new TableEntry("squirrel",37));
        entries.push(new TableEntry("black bear",38));
        entries.push(new TableEntry("dromedary",39));
        entries.push(new TableEntry("dikdik",40));
        entries.push(new TableEntry("fox",42));
        entries.push(new TableEntry("sloth",43));
        entries.push(new TableEntry("otter",44));
        entries.push(new TableEntry("hyena",45));
        entries.push(new TableEntry("snow goat",46));
        entries.push(new TableEntry("tapir",47));
        entries.push(new TableEntry("okapi",48));
        entries.push(new TableEntry("leopard",49));
        entries.push(new TableEntry("rabbit",50));
        entries.push(new TableEntry("hedgehog",51));
        entries.push(new TableEntry("orangutan",52));
        entries.push(new TableEntry("kangaroo",53));
        entries.push(new TableEntry("porcupine",54));
        entries.push(new TableEntry("panda",55));
        entries.push(new TableEntry("possum",56));
        entries.push(new TableEntry("walrus",57));
        entries.push(new TableEntry("hare",58));
        entries.push(new TableEntry("echidna",59));
        entries.push(new TableEntry("red panda",60));
        entries.push(new TableEntry("pig",61));
        entries.push(new TableEntry("grizzly bear",62));
        entries.push(new TableEntry("wild boar",63));
        entries.push(new TableEntry("see elephant",64));
        entries.push(new TableEntry("sheep",65));
        entries.push(new TableEntry("racoon",66));
        entries.push(new TableEntry("ice bear",67));

        entries.push(new TableEntry("eagle",68));
        entries.push(new TableEntry("ara",69));
        entries.push(new TableEntry("auerhahn",70));
        entries.push(new TableEntry("blue-footed booby",71));
        entries.push(new TableEntry("buzzard",72));
        entries.push(new TableEntry("cardinal bird",73));
        entries.push(new TableEntry("ice bird",74));
        entries.push(new TableEntry("emu",75));
        entries.push(new TableEntry("duck",76));
        entries.push(new TableEntry("owl",77));
        entries.push(new TableEntry("pheasant",78));
        entries.push(new TableEntry("flamingo",79));
        entries.push(new TableEntry("bat",80));
        entries.push(new TableEntry("frigatebird",81));
        entries.push(new TableEntry("goose",82));
        entries.push(new TableEntry("uhu",83));
        entries.push(new TableEntry("ibis",84));
        entries.push(new TableEntry("kasuar",85));
        entries.push(new TableEntry("kea",86));
        entries.push(new TableEntry("hummingbird",87));
        entries.push(new TableEntry("crane",88));
        entries.push(new TableEntry("gull",89));
        entries.push(new TableEntry("pelican",90));
        entries.push(new TableEntry("peacock",91));
        entries.push(new TableEntry("puffin",92));
        entries.push(new TableEntry("raven",93));
        entries.push(new TableEntry("screech owl",94));
        entries.push(new TableEntry("swallow",95));
        entries.push(new TableEntry("stork",96));
        entries.push(new TableEntry("deaf",97));
        entries.push(new TableEntry("toco toucan",98));

        entries.push(new TableEntry("baracuda",99));
        entries.push(new TableEntry("blue whale",100));
        entries.push(new TableEntry("colorful fish",101));
        entries.push(new TableEntry("dolphin",102));
        entries.push(new TableEntry("shark",103));
        entries.push(new TableEntry("hammerhead shark",104));
        entries.push(new TableEntry("herring",105));
        entries.push(new TableEntry("lobster",106));
        entries.push(new TableEntry("coral",107));
        entries.push(new TableEntry("manta ray",108));
        entries.push(new TableEntry("octopus",109));
        entries.push(new TableEntry("pyrania",110));
        entries.push(new TableEntry("jellyfish",111));
        entries.push(new TableEntry("sea urchin",112));
        entries.push(new TableEntry("seahorse",113));
        entries.push(new TableEntry("starfish",114));

        entries.push(new TableEntry("ant",115));
        entries.push(new TableEntry("anaconda",116));
        entries.push(new TableEntry("axolotl",117));
        entries.push(new TableEntry("tapeworm",118));
        entries.push(new TableEntry("bee",119));
        entries.push(new TableEntry("frog",120));
        entries.push(new TableEntry("grasshopper",121));
        entries.push(new TableEntry("hornet",122));
        entries.push(new TableEntry("bumblebee",123));
        entries.push(new TableEntry("caiman",124));
        entries.push(new TableEntry("rattlesnake",125));
        entries.push(new TableEntry("crab",126));
        entries.push(new TableEntry("toad",127));
        entries.push(new TableEntry("mamba",128));
        entries.push(new TableEntry("mantis",129));
        entries.push(new TableEntry("dung beetle",130));
        entries.push(new TableEntry("newt",131));
        entries.push(new TableEntry("moth",132));
        entries.push(new TableEntry("slug",133));
        entries.push(new TableEntry("rowing foot crab",134));
        entries.push(new TableEntry("turtle",135));
        entries.push(new TableEntry("butterfly",136));
        entries.push(new TableEntry("black widow",137));
        entries.push(new TableEntry("scarab",138));
        entries.push(new TableEntry("scarab",139));
        entries.push(new TableEntry("tarantula",140));
        entries.push(new TableEntry("millipede",141));
        entries.push(new TableEntry("termite",142));
        entries.push(new TableEntry("waran",143));
        entries.push(new TableEntry("vineyard snail",144));
        entries.push(new TableEntry("wasp",145));
        entries.push(new TableEntry("worm",146));
        entries.push(new TableEntry("raptor",147));
        entries.push(new TableEntry("long-necked dinosaur",148));
        entries.push(new TableEntry("armored dinosaur",149));
        entries.push(new TableEntry("horned dinosaur",150));
        entries.push(new TableEntry("bacteria",151));
        entries.push(new TableEntry("slime",152));
        entries.push(new TableEntry("mushroom",153));

        super(entries, TableTitles.Animal);
        this.functions.push(AlterRace)

    }
}