import {Table} from "../table";
import {TableEntry} from "../tableEntry";
import {Animals} from "./animals";
import {TableTitles} from "../tableTitles";
import {AlterRace} from "./raceTable";

export class AnimalTable extends Table{
    constructor(){
        let entries = [];
        entries.push(new TableEntry(Animals.Goat,1));
        entries.push(new TableEntry("armadillo",2));
        entries.push(new TableEntry("buffalo",3));
        entries.push(new TableEntry("capybara",4));
        entries.push(new TableEntry("badger",5));
        entries.push(new TableEntry("elephant",6));
        entries.push(new TableEntry("earth piglet",7));
        entries.push(new TableEntry("spot musang",8));
        entries.push(new TableEntry("ferret",9));
        entries.push(new TableEntry("gorilla",10));
        entries.push(new TableEntry("hamster",11));
        entries.push(new TableEntry("chicken",12));
        entries.push(new TableEntry("dog",13));
        entries.push(new TableEntry("jaguar",14));
        entries.push(new TableEntry("capuchin monkey",15));
        entries.push(new TableEntry("cat",16));
        entries.push(new TableEntry("coyote",17));
        entries.push(new TableEntry("lama",1));
        entries.push(new TableEntry("lion",1));
        entries.push(new TableEntry("lux",1));
        entries.push(new TableEntry("mole",1));
        entries.push(new TableEntry("hippo",1));
        entries.push(new TableEntry("horse",1));
        entries.push(new TableEntry("rat",1));
        entries.push(new TableEntry("reindeer",1));
        entries.push(new TableEntry("rhino",1));
        entries.push(new TableEntry("rob",1));
        entries.push(new TableEntry("chimpanzee",1));
        entries.push(new TableEntry("platypus",1));
        entries.push(new TableEntry("platypus",1));
        entries.push(new TableEntry("skunk",1));
        entries.push(new TableEntry("gibbon",1));
        entries.push(new TableEntry("elk",1));
        entries.push(new TableEntry("alpaca",1));
        entries.push(new TableEntry("giraffe",1));
        entries.push(new TableEntry("plumploris",1));
        entries.push(new TableEntry("squirrel",1));
        entries.push(new TableEntry("black bear",1));
        entries.push(new TableEntry("dromedary",1));
        entries.push(new TableEntry("dikdik",1));
        entries.push(new TableEntry("fox",1));
        entries.push(new TableEntry("sloth",1));
        entries.push(new TableEntry("otter",1));
        entries.push(new TableEntry("hyena",1));
        entries.push(new TableEntry("snow goat",1));
        entries.push(new TableEntry("tapir",1));
        entries.push(new TableEntry("okapi",1));
        entries.push(new TableEntry("leopard",1));
        entries.push(new TableEntry("rabbit",1));
        entries.push(new TableEntry("hedgehog",1));
        entries.push(new TableEntry("orangutan",1));
        entries.push(new TableEntry("kangaroo",1));
        entries.push(new TableEntry("porcupine",1));
        entries.push(new TableEntry("panda",1));
        entries.push(new TableEntry("possum",1));
        entries.push(new TableEntry("walrus",1));
        entries.push(new TableEntry("hare",1));
        entries.push(new TableEntry("echidna",1));
        entries.push(new TableEntry("red panda",1));
        entries.push(new TableEntry("pig",1));
        entries.push(new TableEntry("grizzly bear",1));
        entries.push(new TableEntry("wild boar",1));
        entries.push(new TableEntry("see elephant",1));
        entries.push(new TableEntry("sheep",1));
        entries.push(new TableEntry("racoon",1));
        entries.push(new TableEntry("ice bear",1));

        entries.push(new TableEntry("eagle",1));
        entries.push(new TableEntry("ara",1));
        entries.push(new TableEntry("auerhahn",1));
        entries.push(new TableEntry("blue-footed booby",1));
        entries.push(new TableEntry("buzzard",1));
        entries.push(new TableEntry("cardinal bird",1));
        entries.push(new TableEntry("ice bird",1));
        entries.push(new TableEntry("emu",1));
        entries.push(new TableEntry("duck",1));
        entries.push(new TableEntry("owl",1));
        entries.push(new TableEntry("pheasant",1));
        entries.push(new TableEntry("flamingo",1));
        entries.push(new TableEntry("bat",1));
        entries.push(new TableEntry("frigatebird",1));
        entries.push(new TableEntry("goose",1));
        entries.push(new TableEntry("uhu",1));
        entries.push(new TableEntry("ibis",1));
        entries.push(new TableEntry("kasuar",1));
        entries.push(new TableEntry("kea",1));
        entries.push(new TableEntry("hummingbird",1));
        entries.push(new TableEntry("crane",1));
        entries.push(new TableEntry("gull",1));
        entries.push(new TableEntry("pelican",1));
        entries.push(new TableEntry("peacock",1));
        entries.push(new TableEntry("puffin",1));
        entries.push(new TableEntry("raven",1));
        entries.push(new TableEntry("screech owl",1));
        entries.push(new TableEntry("swallow",1));
        entries.push(new TableEntry("stork",1));
        entries.push(new TableEntry("deaf",1));
        entries.push(new TableEntry("toco toucan",1));

        entries.push(new TableEntry("baracuda",1));
        entries.push(new TableEntry("blue whale",1));
        entries.push(new TableEntry("colorful fish",1));
        entries.push(new TableEntry("dolphin",1));
        entries.push(new TableEntry("shark",1));
        entries.push(new TableEntry("hammerhead shark",1));
        entries.push(new TableEntry("herring",1));
        entries.push(new TableEntry("lobster",1));
        entries.push(new TableEntry("coral",1));
        entries.push(new TableEntry("manta ray",1));
        entries.push(new TableEntry("octopus",1));
        entries.push(new TableEntry("pyrania",1));
        entries.push(new TableEntry("jellyfish",1));
        entries.push(new TableEntry("sea urchin",1));
        entries.push(new TableEntry("seahorse",1));
        entries.push(new TableEntry("starfish",1));

        entries.push(new TableEntry("ant",1));
        entries.push(new TableEntry("anaconda",1));
        entries.push(new TableEntry("axolotl",1));
        entries.push(new TableEntry("tapeworm",1));
        entries.push(new TableEntry("bee",1));
        entries.push(new TableEntry("frog",1));
        entries.push(new TableEntry("grasshopper",1));
        entries.push(new TableEntry("hornet",1));
        entries.push(new TableEntry("bumblebee",1));
        entries.push(new TableEntry("caiman",1));
        entries.push(new TableEntry("rattlesnake",1));
        entries.push(new TableEntry("crab",1));
        entries.push(new TableEntry("toad",1));
        entries.push(new TableEntry("mamba",1));
        entries.push(new TableEntry("mantis",1));
        entries.push(new TableEntry("dung beetle",1));
        entries.push(new TableEntry("newt",1));
        entries.push(new TableEntry("moth",1));
        entries.push(new TableEntry("slug",1));
        entries.push(new TableEntry("rowing foot crab",1));
        entries.push(new TableEntry("turtle",1));
        entries.push(new TableEntry("butterfly",1));
        entries.push(new TableEntry("black widow",1));
        entries.push(new TableEntry("scarab",1));
        entries.push(new TableEntry("scarab",1));
        entries.push(new TableEntry("tarantula",1));
        entries.push(new TableEntry("millipede",1));
        entries.push(new TableEntry("termite",1));
        entries.push(new TableEntry("waran",1));
        entries.push(new TableEntry("vineyard snail",1));
        entries.push(new TableEntry("wasp",1));
        entries.push(new TableEntry("worm",1));
        entries.push(new TableEntry("raptor",1));
        entries.push(new TableEntry("long-necked dinosaur",1));
        entries.push(new TableEntry("armored dinosaur",1));
        entries.push(new TableEntry("horned dinosaur",1));
        entries.push(new TableEntry("bacteria",1));
        entries.push(new TableEntry("slime",1));
        entries.push(new TableEntry("mushroom",1));

        super(entries, TableTitles.Animal);
        this.functions.push(AlterRace)

    }
}