export enum TableTitles{
    Default = "default title",
    Character = "Character",
    Animal = "Animal",
    Disadvantages = "Disadvantages",
    Race = "Race",
    FantasyCreatures = "FantasyCreatures",
    GermanMaleName = "German Male Names",
    Gender = "Gender",
    Motivation = "Motivation",
    RelationshipType = "Relationship Type",
    Curse="Curse",
    Nobility = "Nobility",
    Profession = "Profession",
    Attributes = "Attributes",
    Senses = "Senses",
    Advantages = "Advantages",
    Alignment = "Alignment",
    Attitude = "Attitude",
    Size = "Size",
    Location = "Location",
    Weather = "Weather",
    Continent = "Continent",
}